// <auto-generated />
using System;
using AmfarAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AmfarAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602215654_ProyectoFinal")]
    partial class ProyectoFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AmfarAPI.Models.Descuento", b =>
                {
                    b.Property<int>("Id_Descuento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Descuento"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activo");

                    b.Property<string>("NombreDescuento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id_Descuento");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("descuentos", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.EspecialidadProfesor", b =>
                {
                    b.Property<int>("IdProfesor")
                        .HasColumnType("integer")
                        .HasColumnName("id_profesor");

                    b.Property<int>("IdInstrumento")
                        .HasColumnType("integer")
                        .HasColumnName("id_instrumento");

                    b.HasKey("IdProfesor", "IdInstrumento");

                    b.HasIndex("IdInstrumento");

                    b.ToTable("especialidad_profesor", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.Estudiante", b =>
                {
                    b.Property<int>("IdPersona")
                        .HasColumnType("integer")
                        .HasColumnName("id_persona");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TieneInstrumento")
                        .HasColumnType("boolean")
                        .HasColumnName("tiene_instrumento");

                    b.HasKey("IdPersona");

                    b.ToTable("estudiante", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.EstudianteTutor", b =>
                {
                    b.Property<int>("IdEstudiante")
                        .HasColumnType("integer")
                        .HasColumnName("id_estudiante");

                    b.Property<int>("IdTutor")
                        .HasColumnType("integer")
                        .HasColumnName("id_tutor");

                    b.HasKey("IdEstudiante", "IdTutor");

                    b.HasIndex("IdTutor");

                    b.ToTable("estudiante_tutor", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.Inscripcion", b =>
                {
                    b.Property<int>("IdInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInscripcion"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoDescuento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoEstudiante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoPlan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activo");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("MontoFinal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdInscripcion");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("inscripciones", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.InscripcionClase", b =>
                {
                    b.Property<int>("IdInscripcionClase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInscripcionClase"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoInstrumento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoProfesor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activo");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<int>("IdInscripcion")
                        .HasColumnType("integer");

                    b.Property<bool>("InstrumentoPrestado")
                        .HasColumnType("boolean");

                    b.HasKey("IdInscripcionClase");

                    b.HasIndex("IdInscripcion");

                    b.ToTable("inscripcion_clases", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.Instrumento", b =>
                {
                    b.Property<int>("IdInstrumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_instrumento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInstrumento"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Disponible")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("StockDisponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stock_disponible");

                    b.Property<int>("StockTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stock_total");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdInstrumento");

                    b.ToTable("instrumento", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPago"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoInscripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activo");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPago");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("pagos", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_persona");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int?>("ProfesorIdProfesor")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("integer");

                    b.HasKey("IdPersona");

                    b.HasIndex("ProfesorIdProfesor");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("persona", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.Plan", b =>
                {
                    b.Property<int>("Id_Plan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Plan"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("EsIndividual")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activo");

                    b.Property<int>("HorasMensuales")
                        .HasColumnType("integer");

                    b.Property<int>("HorasSemanales")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NombrePlan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id_Plan");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("planes", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.PrestamoInstrumento", b =>
                {
                    b.Property<int>("IdPrestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_prestamo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPrestamo"));

                    b.Property<bool>("EsPropio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_propio");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("IdInscripcion")
                        .HasColumnType("integer")
                        .HasColumnName("id_inscripcion");

                    b.Property<int>("IdInstrumento")
                        .HasColumnType("integer")
                        .HasColumnName("id_instrumento");

                    b.HasKey("IdPrestamo");

                    b.HasIndex("IdInstrumento");

                    b.ToTable("prestamo_instrumento", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.Profesor", b =>
                {
                    b.Property<int>("IdProfesor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_profesor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProfesor"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdPersona")
                        .HasColumnType("integer")
                        .HasColumnName("id_persona");

                    b.HasKey("IdProfesor");

                    b.HasIndex("IdPersona");

                    b.ToTable("profesor", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.Recibo", b =>
                {
                    b.Property<int>("IdRecibo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_recibo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRecibo"));

                    b.Property<string>("CodigoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_pago");

                    b.Property<string>("DatosAlumno")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("datos_alumno");

                    b.Property<string>("EmitidoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("emitido_por");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto");

                    b.Property<string>("NombrePlan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_plan");

                    b.Property<string>("NumeroRecibo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_recibo");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("periodo");

                    b.HasKey("IdRecibo");

                    b.HasIndex("CodigoPago");

                    b.HasIndex("NumeroRecibo")
                        .IsUnique();

                    b.ToTable("recibo", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.Tutor", b =>
                {
                    b.Property<int>("IdPersona")
                        .HasColumnType("integer")
                        .HasColumnName("id_persona");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Parentesco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parentesco");

                    b.HasKey("IdPersona");

                    b.ToTable("tutor", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contrasena");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<int>("IdPersona")
                        .HasColumnType("integer")
                        .HasColumnName("id_persona");

                    b.Property<int>("Rol")
                        .HasColumnType("integer")
                        .HasColumnName("rol");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdPersona");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.EspecialidadProfesor", b =>
                {
                    b.HasOne("AmfarAPI.Models.Instrumento", "Instrumento")
                        .WithMany("EspecialidadProfesores")
                        .HasForeignKey("IdInstrumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmfarAPI.Models.Profesor", "Profesor")
                        .WithMany("Especialidades")
                        .HasForeignKey("IdProfesor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrumento");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("AmfarAPI.Models.Estudiante", b =>
                {
                    b.HasOne("AmfarAPI.Models.Persona", "Persona")
                        .WithOne("Estudiante")
                        .HasForeignKey("AmfarAPI.Models.Estudiante", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("AmfarAPI.Models.EstudianteTutor", b =>
                {
                    b.HasOne("AmfarAPI.Models.Estudiante", "Estudiante")
                        .WithMany("EstudiantesTutores")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmfarAPI.Models.Tutor", "Tutor")
                        .WithMany("EstudiantesTutores")
                        .HasForeignKey("IdTutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("AmfarAPI.Models.InscripcionClase", b =>
                {
                    b.HasOne("AmfarAPI.Models.Inscripcion", "Inscripcion")
                        .WithMany("InscripcionClases")
                        .HasForeignKey("IdInscripcion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("AmfarAPI.Models.Persona", b =>
                {
                    b.HasOne("AmfarAPI.Models.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorIdProfesor");

                    b.HasOne("AmfarAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("Profesor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AmfarAPI.Models.PrestamoInstrumento", b =>
                {
                    b.HasOne("AmfarAPI.Models.Instrumento", "Instrumento")
                        .WithMany("Prestamos")
                        .HasForeignKey("IdInstrumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instrumento");
                });

            modelBuilder.Entity("AmfarAPI.Models.Profesor", b =>
                {
                    b.HasOne("AmfarAPI.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("AmfarAPI.Models.Tutor", b =>
                {
                    b.HasOne("AmfarAPI.Models.Persona", "Persona")
                        .WithOne("Tutor")
                        .HasForeignKey("AmfarAPI.Models.Tutor", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("AmfarAPI.Models.Usuario", b =>
                {
                    b.HasOne("AmfarAPI.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("AmfarAPI.Models.Estudiante", b =>
                {
                    b.Navigation("EstudiantesTutores");
                });

            modelBuilder.Entity("AmfarAPI.Models.Inscripcion", b =>
                {
                    b.Navigation("InscripcionClases");
                });

            modelBuilder.Entity("AmfarAPI.Models.Instrumento", b =>
                {
                    b.Navigation("EspecialidadProfesores");

                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("AmfarAPI.Models.Persona", b =>
                {
                    b.Navigation("Estudiante");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("AmfarAPI.Models.Profesor", b =>
                {
                    b.Navigation("Especialidades");
                });

            modelBuilder.Entity("AmfarAPI.Models.Tutor", b =>
                {
                    b.Navigation("EstudiantesTutores");
                });
#pragma warning restore 612, 618
        }
    }
}
