// <auto-generated />
using System;
using AmfarAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AmfarAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AmfarAPI.Models.EspecialidadProfesor", b =>
                {
                    b.Property<int>("IdProfesor")
                        .HasColumnType("integer")
                        .HasColumnName("id_profesor");

                    b.Property<int>("IdInstrumento")
                        .HasColumnType("integer")
                        .HasColumnName("id_instrumento");

                    b.HasKey("IdProfesor", "IdInstrumento");

                    b.HasIndex("IdInstrumento");

                    b.ToTable("especialidad_profesor", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.Estudiante", b =>
                {
                    b.Property<int>("IdPersona")
                        .HasColumnType("integer")
                        .HasColumnName("id_persona");

                    b.Property<bool>("TieneInstrumento")
                        .HasColumnType("boolean")
                        .HasColumnName("tiene_instrumento");

                    b.HasKey("IdPersona");

                    b.ToTable("estudiante", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.EstudianteTutor", b =>
                {
                    b.Property<int>("IdEstudiante")
                        .HasColumnType("integer")
                        .HasColumnName("id_estudiante");

                    b.Property<int>("IdTutor")
                        .HasColumnType("integer")
                        .HasColumnName("id_tutor");

                    b.HasKey("IdEstudiante", "IdTutor");

                    b.HasIndex("IdTutor");

                    b.ToTable("estudiante_tutor", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.Instrumento", b =>
                {
                    b.Property<int>("IdInstrumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_instrumento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInstrumento"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Disponible")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("StockDisponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stock_disponible");

                    b.Property<int>("StockTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stock_total");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdInstrumento");

                    b.ToTable("instrumento", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_persona");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<int?>("EstudianteIdPersona")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int?>("ProfesorIdProfesor")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<int?>("TutorIdPersona")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("integer");

                    b.HasKey("IdPersona");

                    b.HasIndex("EstudianteIdPersona");

                    b.HasIndex("ProfesorIdProfesor");

                    b.HasIndex("TutorIdPersona");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("persona", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.PrestamoInstrumento", b =>
                {
                    b.Property<int>("IdPrestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_prestamo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPrestamo"));

                    b.Property<bool>("EsPropio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_propio");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("IdInscripcion")
                        .HasColumnType("integer")
                        .HasColumnName("id_inscripcion");

                    b.Property<int>("IdInstrumento")
                        .HasColumnType("integer")
                        .HasColumnName("id_instrumento");

                    b.HasKey("IdPrestamo");

                    b.HasIndex("IdInstrumento");

                    b.ToTable("prestamo_instrumento", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.Profesor", b =>
                {
                    b.Property<int>("IdProfesor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_profesor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProfesor"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdPersona")
                        .HasColumnType("integer")
                        .HasColumnName("id_persona");

                    b.HasKey("IdProfesor");

                    b.HasIndex("IdPersona");

                    b.ToTable("profesor", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.Tutor", b =>
                {
                    b.Property<int>("IdPersona")
                        .HasColumnType("integer")
                        .HasColumnName("id_persona");

                    b.Property<string>("Parentesco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parentesco");

                    b.HasKey("IdPersona");

                    b.ToTable("tutor", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contrasena");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<int>("IdPersona")
                        .HasColumnType("integer")
                        .HasColumnName("id_persona");

                    b.Property<int>("Rol")
                        .HasColumnType("integer")
                        .HasColumnName("rol");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdPersona");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("AmfarAPI.Models.EspecialidadProfesor", b =>
                {
                    b.HasOne("AmfarAPI.Models.Instrumento", "Instrumento")
                        .WithMany("EspecialidadProfesores")
                        .HasForeignKey("IdInstrumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AmfarAPI.Models.Profesor", "Profesor")
                        .WithMany("Especialidades")
                        .HasForeignKey("IdProfesor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrumento");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("AmfarAPI.Models.Estudiante", b =>
                {
                    b.HasOne("AmfarAPI.Models.Persona", "Persona")
                        .WithOne()
                        .HasForeignKey("AmfarAPI.Models.Estudiante", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("AmfarAPI.Models.EstudianteTutor", b =>
                {
                    b.HasOne("AmfarAPI.Models.Estudiante", "Estudiante")
                        .WithMany("EstudiantesTutores")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmfarAPI.Models.Tutor", "Tutor")
                        .WithMany("EstudiantesTutores")
                        .HasForeignKey("IdTutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("AmfarAPI.Models.Persona", b =>
                {
                    b.HasOne("AmfarAPI.Models.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteIdPersona");

                    b.HasOne("AmfarAPI.Models.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("ProfesorIdProfesor");

                    b.HasOne("AmfarAPI.Models.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorIdPersona");

                    b.HasOne("AmfarAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("Estudiante");

                    b.Navigation("Profesor");

                    b.Navigation("Tutor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AmfarAPI.Models.PrestamoInstrumento", b =>
                {
                    b.HasOne("AmfarAPI.Models.Instrumento", "Instrumento")
                        .WithMany("Prestamos")
                        .HasForeignKey("IdInstrumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instrumento");
                });

            modelBuilder.Entity("AmfarAPI.Models.Profesor", b =>
                {
                    b.HasOne("AmfarAPI.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("AmfarAPI.Models.Tutor", b =>
                {
                    b.HasOne("AmfarAPI.Models.Persona", "Persona")
                        .WithOne()
                        .HasForeignKey("AmfarAPI.Models.Tutor", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("AmfarAPI.Models.Usuario", b =>
                {
                    b.HasOne("AmfarAPI.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("AmfarAPI.Models.Estudiante", b =>
                {
                    b.Navigation("EstudiantesTutores");
                });

            modelBuilder.Entity("AmfarAPI.Models.Instrumento", b =>
                {
                    b.Navigation("EspecialidadProfesores");

                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("AmfarAPI.Models.Profesor", b =>
                {
                    b.Navigation("Especialidades");
                });

            modelBuilder.Entity("AmfarAPI.Models.Tutor", b =>
                {
                    b.Navigation("EstudiantesTutores");
                });
#pragma warning restore 612, 618
        }
    }
}
